name: Prueba

on:
  workflow_dispatch:
    inputs:
      destinations:
        type: choice
        description: "Select the destination"
        default: destination1
        required: true
        options: ${{ steps.get_options.outputs.options }}

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Get options from file
        id: get_options
        run: echo "::set-output name=options::$(cat options.txt)"
      - name: Send greeting
        run: echo "hola"
